-- LexRAG schema — pgvector + HNSW (dense) + GIN full-text (BM25-like, sparse).
-- Applied automatically by docker-entrypoint-initdb.d on first container boot,
-- and idempotently by LexRag.Index.PgvectorSchema at startup.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS document_chunks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_key    UUID        NOT NULL UNIQUE,
    source_file  TEXT        NOT NULL,
    chunk_index  INT         NOT NULL,
    content      TEXT        NOT NULL,
    -- 1536 = OpenAI text-embedding-3-small. The fake hash generator also emits 1536-d
    -- vectors so the schema is identical whether running with or without an API key.
    embedding    VECTOR(1536),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Dense ANN: HNSW + cosine. Legal docs vary wildly in length → direction, not magnitude.
-- Production-leaning defaults: m=16, ef_construction=128 (vs library default 64).
CREATE INDEX IF NOT EXISTS ix_document_chunks_embedding_hnsw
    ON document_chunks USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 128);

-- Sparse / exact-term: GIN over Portuguese tsvector (process numbers, statute articles).
CREATE INDEX IF NOT EXISTS ix_document_chunks_content_fts
    ON document_chunks USING gin (to_tsvector('portuguese', content));

CREATE INDEX IF NOT EXISTS ix_document_chunks_source_file
    ON document_chunks (source_file);
