namespace LexRag.Index;

// Kept in sync with db/init/01-schema.sql so app-applied and container-applied SQL never drift.
public static class PgVectorSchema
{
    public const string CreateSql = """
        CREATE EXTENSION IF NOT EXISTS vector;

        CREATE TABLE IF NOT EXISTS document_chunks (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chunk_key    UUID        NOT NULL UNIQUE,
            source_file  TEXT        NOT NULL,
            chunk_index  INT         NOT NULL,
            content      TEXT        NOT NULL,
            embedding    VECTOR(1536),
            created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE INDEX IF NOT EXISTS ix_document_chunks_embedding_hnsw
            ON document_chunks USING hnsw (embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 128);

        CREATE INDEX IF NOT EXISTS ix_document_chunks_content_fts
            ON document_chunks USING gin (to_tsvector('portuguese', content));

        CREATE INDEX IF NOT EXISTS ix_document_chunks_source_file
            ON document_chunks (source_file);
        """;
}
